spring:
  application:
    name: beneficiary-collab-service

aws:
  dynamodb:
    region: us-east-1
    tableName: beneficiary-collaboration-table-dp

logging:
  level:
    root: info
    com.hackathon.springboard: debug
