spring:
  application:
    name: beneficiary-collab-service

aws:
  dynamodb:
    region: us-east-1
    end-point: http://localhost:8000
    local: true
    tableName: beneficiary-collaboration-table

logging:
  level:
    root: info
    com.hackathon.springboard: debug
