aws:
  dynamodb:
    region: us-east-1
    endpoint: http://localhost:8000
    local: true
    tableName: beneficiary-collaboration-table-dp

logging:
  level:
    root: info
    com.hackathon.springboard: debug
    software: error